version: '3.1'
services:
  yit-education-eureka:
    restart: always
    image: 192.168.93.148:5000/yit-education-user-service:v1.0.0
    container_name: yit-education-user-service
    ports:
      - 5720:5720
    networks:
      - cloud

networks:
  cloud:
    external:
      name: spring_cloud